### ISSUE TITLE
What license is this project under? Consider adding a license file?

### ISSUE THREAD

**Issue by fuzzzerd** [wimdecorte/FMdotNet__DataAPI#2]
Without a license file we don't know how we can use this project. I maintain a similar project, and I'd be stoked to share ideas/code/testing.

**Comment by wimdecorte** [comment]
MIT license.  I'll add it.
Happy go share ideas and potentially merge the two projects...

**Comment by wimdecorte** [comment]
MIT license file added.

**Comment by fuzzzerd** [comment]
I originally forked your xml fmdotnet to add some advanced query support. 

Since then, I started a new project with a slightly modified api, that can work against either Filemaker xml or data api: https://fmdata.io. I'd love to collaborate and share he ideas. Right now that project is all geared toward strongly typed objects mapping to layouts. 

I would like to add support for the more dynamic results that you have here as well. I'd be open to further discussion around merging the projects, If we've got similar goals.
